# Deliverable 2. Create a Customer Travel Destinations Map.
----
1. Create a folder called `Vacation_Search` to save all the files related with this deliverable.

2. Download the `Vacation_Search_starter_code.ipynb` Jupyter notebook,save it into your `Vacation_Search folder`, and rename it as `Vacation_Search.ipynb`.

3. In the `Vacation_Search.ipynb` file, ensure that the dependencies and the Google API key is imported correctly.

4. From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame named `city_data_df`.

5. Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

6. Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected. Name the DataFrame as `preferred_cities_df`.

7. Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

8. Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

9. Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

10. Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

11. Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

12. Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

13. Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

14. Review the formatting template provided that you'll use to add an information box to each marker in the map. In the pop-up for each city you'll add:

    1. The city name.

    2. The country code.

    3. The weather description and maximum temperature for the city.

15. Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

16. Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

17. Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

18. Take a screenshot of your map and save it to the `Vacation_Search` folder as `WeatherPy_vacation_map.png`.
---

## Ensure that the dependencies and the Google API key is imported correctly.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import Google API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

## From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame.

In [4]:
# Set the file path to import the WeatherPy_database.csv file
file_path = "../Weather_database/WeatherPy_Database.csv"

# Load the CSV file into a Pandas DataFrame
city_data_df = pd.read_csv(file_path)

# Display sample data
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Krasnoarmeyskiy,RU,47.0114,42.2072,45.21,53,1,4.81,clear sky
1,1,Mto Wa Mbu,TZ,-3.3500,35.8500,69.96,71,36,4.83,scattered clouds
2,2,Chervishevo,RU,56.9464,65.4278,43.09,84,100,7.00,overcast clouds
3,3,Arraial Do Cabo,BR,-22.9661,-42.0278,75.06,83,0,18.41,clear sky
4,4,Salinas,US,36.6777,-121.6555,80.56,54,0,11.50,clear sky

## Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

In [5]:
# Prompt the user to enter the minimum temperature criteria
min_temp = float(input("What is the minimum temperature you would like for your trip?"))

# Prompt the user to enter the maximum temperature criteria
max_temp = float(input("What is the maximum temperature you would like for your trip?"))

What is the minimum temperature you would like for your trip?60
What is the maximum temperature you would like for your trip?75

## Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected.

In [6]:
# Filter the city_data_df DataFrame to find the cities that fit the criteria using the loc Pandas function
preferred_cities_df =  city_data_df.loc[(city_data_df["Max Temp"] <= max_temp)&(city_data_df["Max Temp"]>=min_temp)]

                                    
# Display sample data
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Mto Wa Mbu,TZ,-3.3500,35.8500,69.96,71,36,4.83,scattered clouds
6,6,Cape Town,ZA,-33.9258,18.4232,64.09,79,78,11.01,broken clouds
8,8,Mahebourg,MU,-20.4081,57.7000,70.09,73,20,5.75,few clouds
9,9,Port Shepstone,ZA,-30.7414,30.4550,71.98,90,34,11.81,scattered clouds
10,10,Rio Tinto,PT,41.1826,-8.5581,65.28,85,0,7.00,clear sky
15,15,Bambous Virieux,MU,-20.3428,57.7575,70.05,73,20,5.75,few clouds
25,25,East London,ZA,-33.0153,27.9116,67.05,86,4,7.27,clear sky
26,26,Hualmay,PE,-11.0964,-77.6139,64.72,76,29,9.66,scattered clouds
31,31,Saint-Philippe,RE,-21.3585,55.7679,67.59,81,37,7.92,scattered clouds
34,34,San Juan,AR,-31.5375,-68.5364,69.19,48,79,21.21,broken clouds

## Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

In [9]:
# Drop any empty rows in the preferred_cities_df DataFrame and create a new DataFrame.
clean_travel_cities = preferred_cities_df.dropna()

# Display sample data
clean_travel_cities.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Mto Wa Mbu,TZ,-3.3500,35.8500,69.96,71,36,4.83,scattered clouds
6,6,Cape Town,ZA,-33.9258,18.4232,64.09,79,78,11.01,broken clouds
8,8,Mahebourg,MU,-20.4081,57.7000,70.09,73,20,5.75,few clouds
9,9,Port Shepstone,ZA,-30.7414,30.4550,71.98,90,34,11.81,scattered clouds
10,10,Rio Tinto,PT,41.1826,-8.5581,65.28,85,0,7.00,clear sky
15,15,Bambous Virieux,MU,-20.3428,57.7575,70.05,73,20,5.75,few clouds
25,25,East London,ZA,-33.0153,27.9116,67.05,86,4,7.27,clear sky
26,26,Hualmay,PE,-11.0964,-77.6139,64.72,76,29,9.66,scattered clouds
31,31,Saint-Philippe,RE,-21.3585,55.7679,67.59,81,37,7.92,scattered clouds
34,34,San Juan,AR,-31.5375,-68.5364,69.19,48,79,21.21,broken clouds

## Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

In [10]:
# Create DataFrame called hotel_df by copying some columns from the clean_travel_cities DataFrame.
hotel_df= clean_travel_cities[["City","Country","Max Temp","Current Description","Lat","Lng"]].copy()

# Display sample data
hotel_df.head(10)

               City Country  Max Temp Current Description      Lat      Lng
1        Mto Wa Mbu      TZ     69.96    scattered clouds  -3.3500  35.8500
6         Cape Town      ZA     64.09       broken clouds -33.9258  18.4232
8         Mahebourg      MU     70.09          few clouds -20.4081  57.7000
9    Port Shepstone      ZA     71.98    scattered clouds -30.7414  30.4550
10        Rio Tinto      PT     65.28           clear sky  41.1826  -8.5581
15  Bambous Virieux      MU     70.05          few clouds -20.3428  57.7575
25      East London      ZA     67.05           clear sky -33.0153  27.9116
26          Hualmay      PE     64.72    scattered clouds -11.0964 -77.6139
31   Saint-Philippe      RE     67.59    scattered clouds -21.3585  55.7679
34         San Juan      AR     69.19       broken clouds -31.5375 -68.5364

## Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

In [11]:
# Add a new empty column, "Hotel Name", to the hotel_df DataFrame
hotel_df["Hotel Name"]=""

# Display sample data
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Mto Wa Mbu,TZ,69.96,scattered clouds,-3.3500,35.8500,
6,Cape Town,ZA,64.09,broken clouds,-33.9258,18.4232,
8,Mahebourg,MU,70.09,few clouds,-20.4081,57.7000,
9,Port Shepstone,ZA,71.98,scattered clouds,-30.7414,30.4550,
10,Rio Tinto,PT,65.28,clear sky,41.1826,-8.5581,
15,Bambous Virieux,MU,70.05,few clouds,-20.3428,57.7575,
25,East London,ZA,67.05,clear sky,-33.0153,27.9116,
26,Hualmay,PE,64.72,scattered clouds,-11.0964,-77.6139,
31,Saint-Philippe,RE,67.59,scattered clouds,-21.3585,55.7679,
34,San Juan,AR,69.19,broken clouds,-31.5375,-68.5364,

## Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

In [12]:
# Review the parameters to search for a hotel
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

## Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

In [13]:
# Iterate through the hotel DataFrame 
for index, row in hotel_df.iterrows():
    # Fetch latitude and longitude from the DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude as parameters to the params dictionary
    params["location"] = f"{lat},{lng}"
    
    # Set up the base URL for the Google Directions API to get JSON data
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make an API request and retrieve the JSON data from the hotel search
    hotels = requests.get(base_url, params=params).json()
    
    # Get the first hotel from the results and store the name, if a hotel isn't found skip the city
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [22]:
# Display sample data
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Mto Wa Mbu,TZ,69.96,scattered clouds,-3.3500,35.8500,Fanaka Safaris Campsite & Lodges
6,Cape Town,ZA,64.09,broken clouds,-33.9258,18.4232,"Radisson Blu Hotel Waterfront, Cape Town"
8,Mahebourg,MU,70.09,few clouds,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
9,Port Shepstone,ZA,71.98,scattered clouds,-30.7414,30.4550,My Den Beachfront Bed and Breakfast | Self-Cat...
10,Rio Tinto,PT,65.28,clear sky,41.1826,-8.5581,Axis Porto Business & SPA Hotel
15,Bambous Virieux,MU,70.05,few clouds,-20.3428,57.7575,Casa Tia Villa
25,East London,ZA,67.05,clear sky,-33.0153,27.9116,Tu Casa
26,Hualmay,PE,64.72,scattered clouds,-11.0964,-77.6139,Hotel Villa Kitzia Huacho
31,Saint-Philippe,RE,67.59,scattered clouds,-21.3585,55.7679,Le four à pain
34,San Juan,AR,69.19,broken clouds,-31.5375,-68.5364,Hotel Provincial
38,Cidreira,BR,63.90,overcast clouds,-30.1811,-50.2056,Hotel Castelo
39,Port Elizabeth,ZA,63.32,broken clouds,-33.9180,25.5701,39 On Nile Guest House
41,Niort,FR,61.18,broken clouds,46.3333,-0.3333,Hôtel Première Classe Niort La Crèche
42,Mauganj,IN,69.22,clear sky,24.6833,81.8833,Hotel Shagun Palace & Marriage Garden
46,Makrana,IN,71.62,clear sky,27.0500,74.7167,Ganpati Guest House
47,Muros,ES,61.84,clear sky,42.7762,-9.0603,Apartment Av. Castelao
53,Colares,PT,68.76,clear sky,38.7992,-9.4469,Arribas Sintra Hotel
57,Ponta Do Sol,PT,74.01,light rain,32.6667,-17.1000,Hotel do Campo
58,Culfa,AZ,62.47,overcast clouds,38.9558,45.6308,Hotel Araz
70,Saumur,FR,61.90,overcast clouds,47.3333,-0.2500,Hôtel la Longue Vue
73,Souillac,MU,70.18,few clouds,-20.5167,57.5167,Shanti Maurice Resort & Spa
79,Mizdah,LY,62.29,clear sky,31.4451,12.9801,محمدالمبروك الاريقط
88,Nampula,MZ,73.35,clear sky,-15.1165,39.2666,Ruby Backpackers
90,Antalaha,MG,65.46,scattered clouds,-14.9003,50.2788,Hotel Vitasoa
91,Challans,FR,61.00,broken clouds,46.8436,-1.8749,Citotel Le Challans
92,Rivera,UY,61.05,overcast clouds,-30.9053,-55.5508,Emirates Hotel e Suítes
94,Boundiali,CI,74.62,scattered clouds,9.5217,-6.4869,Hotel Paysan Boundiali
98,Port Alfred,ZA,63.18,scattered clouds,-33.5906,26.8910,The Halyards Hotel
100,Lixourion,GR,66.11,clear sky,38.2019,20.4314,Hotel Summery
103,Chiman,PK,68.22,clear sky,32.5463,73.8138,Master Muhammad zafar iqbal
...,...,...,...,...,...,...,...
477,Westport,US,64.44,clear sky,41.1415,-73.3579,The Westport Inn
480,Afonso Claudio,BR,69.24,broken clouds,-20.0742,-41.1239,Pousada Afonso Cláudio
481,Alassio,IT,69.48,broken clouds,44.0039,8.1671,Hotel Toscana
485,San Gavino Monreale,IT,67.46,overcast clouds,39.5514,8.7917,Hotel Crocus
490,Hyeres,FR,67.68,clear sky,43.1167,6.1167,ibis budget Hyères Centre-Ville
497,Lyantonde,UG,60.64,broken clouds,-0.4031,31.1572,Novella Hotel & Spa
501,Ancud,CL,70.23,clear sky,-41.8697,-73.8203,Hotel Arena Gruesa
502,Siva,EG,72.30,broken clouds,29.2041,25.5195,Qasr Alzaytuna Inn
504,Manakara,MG,64.38,clear sky,-22.1333,48.0167,La Residence Manakara
511,Ambilobe,MG,69.15,broken clouds,-13.2000,49.0500,Hôtel & Restaurant DIANA Ambilobe
513,Farkhor,TJ,64.06,overcast clouds,37.4922,69.4036,Khonai Abdulkhayrov
514,Andrelandia,BR,67.64,overcast clouds,-21.7397,-44.3092,Hotel Real
516,Lancaster,US,60.30,overcast clouds,40.2504,-76.2499,Refreshing Mountain Retreat and Adventure Center
526,Tasgaon,IN,72.90,overcast clouds,17.0333,74.6000,Hotel Shree Siddhivinayak
528,Shujaabad,PK,73.45,clear sky,29.8797,71.2931,Amir jewellery collection
530,Vitry-Le-Francois,FR,63.01,light rain,48.7333,4.5833,Hôtel Tambourin
533,Uravakonda,IN,74.03,overcast clouds,14.9500,77.2667,Divya Lodge
538,Camamu,BR,71.35,clear sky,-13.9447,-39.1039,Hotel Rio Acarai
542,Mocuba,MZ,70.50,clear sky,-16.8392,36.9856,Phama Lodge
544,Calama,CL,68.49,clear sky,-22.4667,-68.9333,Park Hotel Calama
554,Hima,UG,63.84,overcast clouds,0.2958,30.1804,Bike bar and Lodge
559,Rio Gallegos,AR,68.05,clear sky,-51.6226,-69.2181,Hotel Santa Cruz
560,Antsohihy,MG,70.84,clear sky,-14.8796,47.9875,Hotel de Ville
561,Tuljapur,IN,72.91,overcast clouds,18.0000,76.0833,Hotel Son of Sun
564,Sao Gabriel Da Cachoeira,BR,74.37,broken clouds,-0.1303,-67.0892,Alarne - Área De Lazer Do Alto Rio Negro
565,Camana,PE,63.07,broken clouds,-16.6228,-72.7111,Hostal Morales
566,Joao Alfredo,BR,69.24,overcast clouds,-7.8558,-35.5883,Cristal Hotel
568,Huarmey,PE,63.95,few clouds,-10.0681,-78.1522,Hotel Miramar
569,Santo Antonio Do Sudoeste,BR,67.32,moderate rain,-26.0736,-53.7253,Hotel Frontera
570,Jalu,LY,66.60,clear sky,29.0331,21.5482,صاحبة الفخامة

## Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

In [18]:
import numpy as np

In [29]:
# Drop the rows where there is no Hotel Name.
hotel_df["Hotel Name"].replace('', np.nan, inplace=True)

clean_hotel_df = hotel_df.dropna(subset=['Hotel Name'], inplace=True)

# Display sample data
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Mto Wa Mbu,TZ,69.96,scattered clouds,-3.3500,35.8500,Fanaka Safaris Campsite & Lodges
6,Cape Town,ZA,64.09,broken clouds,-33.9258,18.4232,"Radisson Blu Hotel Waterfront, Cape Town"
8,Mahebourg,MU,70.09,few clouds,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
9,Port Shepstone,ZA,71.98,scattered clouds,-30.7414,30.4550,My Den Beachfront Bed and Breakfast | Self-Cat...
10,Rio Tinto,PT,65.28,clear sky,41.1826,-8.5581,Axis Porto Business & SPA Hotel
15,Bambous Virieux,MU,70.05,few clouds,-20.3428,57.7575,Casa Tia Villa
25,East London,ZA,67.05,clear sky,-33.0153,27.9116,Tu Casa
26,Hualmay,PE,64.72,scattered clouds,-11.0964,-77.6139,Hotel Villa Kitzia Huacho
31,Saint-Philippe,RE,67.59,scattered clouds,-21.3585,55.7679,Le four à pain
34,San Juan,AR,69.19,broken clouds,-31.5375,-68.5364,Hotel Provincial
38,Cidreira,BR,63.90,overcast clouds,-30.1811,-50.2056,Hotel Castelo
39,Port Elizabeth,ZA,63.32,broken clouds,-33.9180,25.5701,39 On Nile Guest House
41,Niort,FR,61.18,broken clouds,46.3333,-0.3333,Hôtel Première Classe Niort La Crèche
42,Mauganj,IN,69.22,clear sky,24.6833,81.8833,Hotel Shagun Palace & Marriage Garden
46,Makrana,IN,71.62,clear sky,27.0500,74.7167,Ganpati Guest House
47,Muros,ES,61.84,clear sky,42.7762,-9.0603,Apartment Av. Castelao
53,Colares,PT,68.76,clear sky,38.7992,-9.4469,Arribas Sintra Hotel
57,Ponta Do Sol,PT,74.01,light rain,32.6667,-17.1000,Hotel do Campo
58,Culfa,AZ,62.47,overcast clouds,38.9558,45.6308,Hotel Araz
70,Saumur,FR,61.90,overcast clouds,47.3333,-0.2500,Hôtel la Longue Vue
73,Souillac,MU,70.18,few clouds,-20.5167,57.5167,Shanti Maurice Resort & Spa
79,Mizdah,LY,62.29,clear sky,31.4451,12.9801,محمدالمبروك الاريقط
88,Nampula,MZ,73.35,clear sky,-15.1165,39.2666,Ruby Backpackers
90,Antalaha,MG,65.46,scattered clouds,-14.9003,50.2788,Hotel Vitasoa
91,Challans,FR,61.00,broken clouds,46.8436,-1.8749,Citotel Le Challans
92,Rivera,UY,61.05,overcast clouds,-30.9053,-55.5508,Emirates Hotel e Suítes
94,Boundiali,CI,74.62,scattered clouds,9.5217,-6.4869,Hotel Paysan Boundiali
98,Port Alfred,ZA,63.18,scattered clouds,-33.5906,26.8910,The Halyards Hotel
100,Lixourion,GR,66.11,clear sky,38.2019,20.4314,Hotel Summery
103,Chiman,PK,68.22,clear sky,32.5463,73.8138,Master Muhammad zafar iqbal
...,...,...,...,...,...,...,...
477,Westport,US,64.44,clear sky,41.1415,-73.3579,The Westport Inn
480,Afonso Claudio,BR,69.24,broken clouds,-20.0742,-41.1239,Pousada Afonso Cláudio
481,Alassio,IT,69.48,broken clouds,44.0039,8.1671,Hotel Toscana
485,San Gavino Monreale,IT,67.46,overcast clouds,39.5514,8.7917,Hotel Crocus
490,Hyeres,FR,67.68,clear sky,43.1167,6.1167,ibis budget Hyères Centre-Ville
497,Lyantonde,UG,60.64,broken clouds,-0.4031,31.1572,Novella Hotel & Spa
501,Ancud,CL,70.23,clear sky,-41.8697,-73.8203,Hotel Arena Gruesa
502,Siva,EG,72.30,broken clouds,29.2041,25.5195,Qasr Alzaytuna Inn
504,Manakara,MG,64.38,clear sky,-22.1333,48.0167,La Residence Manakara
511,Ambilobe,MG,69.15,broken clouds,-13.2000,49.0500,Hôtel & Restaurant DIANA Ambilobe
513,Farkhor,TJ,64.06,overcast clouds,37.4922,69.4036,Khonai Abdulkhayrov
514,Andrelandia,BR,67.64,overcast clouds,-21.7397,-44.3092,Hotel Real
516,Lancaster,US,60.30,overcast clouds,40.2504,-76.2499,Refreshing Mountain Retreat and Adventure Center
526,Tasgaon,IN,72.90,overcast clouds,17.0333,74.6000,Hotel Shree Siddhivinayak
528,Shujaabad,PK,73.45,clear sky,29.8797,71.2931,Amir jewellery collection
530,Vitry-Le-Francois,FR,63.01,light rain,48.7333,4.5833,Hôtel Tambourin
533,Uravakonda,IN,74.03,overcast clouds,14.9500,77.2667,Divya Lodge
538,Camamu,BR,71.35,clear sky,-13.9447,-39.1039,Hotel Rio Acarai
542,Mocuba,MZ,70.50,clear sky,-16.8392,36.9856,Phama Lodge
544,Calama,CL,68.49,clear sky,-22.4667,-68.9333,Park Hotel Calama
554,Hima,UG,63.84,overcast clouds,0.2958,30.1804,Bike bar and Lodge
559,Rio Gallegos,AR,68.05,clear sky,-51.6226,-69.2181,Hotel Santa Cruz
560,Antsohihy,MG,70.84,clear sky,-14.8796,47.9875,Hotel de Ville
561,Tuljapur,IN,72.91,overcast clouds,18.0000,76.0833,Hotel Son of Sun
564,Sao Gabriel Da Cachoeira,BR,74.37,broken clouds,-0.1303,-67.0892,Alarne - Área De Lazer Do Alto Rio Negro
565,Camana,PE,63.07,broken clouds,-16.6228,-72.7111,Hostal Morales
566,Joao Alfredo,BR,69.24,overcast clouds,-7.8558,-35.5883,Cristal Hotel
568,Huarmey,PE,63.95,few clouds,-10.0681,-78.1522,Hotel Miramar
569,Santo Antonio Do Sudoeste,BR,67.32,moderate rain,-26.0736,-53.7253,Hotel Frontera
570,Jalu,LY,66.60,clear sky,29.0331,21.5482,صاحبة الفخامة

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

In [26]:
# In case of an empty DataFrame, load the sample data provided
#clean_hotel_df = pd.read_csv("WeatherPy_vacation-backup.csv")
#clean_hotel_df.head(10)

## Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

In [31]:
# Set the file name.
output_data_file = "WeatherPy_vacation.csv"

# Create a CSV file by using the clean_hotel_df DataFrame
hotel_df.to_csv(output_data_file)

### Review the formatting template provided that you'll use to add an information box to each marker in the map.

In the pop-up for each city you'll add: 

1. The city name

2. The country code

3. The weather description and maximum temperature for the city

In [33]:
# Review the formatting template provided
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

## Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

In [34]:
# Get the data from each row in the clean_hotel_df DataFrame, add it to the formatting template, and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# Display sample data
hotel_info[:10]

['\n<dl>\n<dt>Hotel Name</dt><dd>Fanaka Safaris Campsite & Lodges</dd>\n<dt>City</dt><dd>Mto Wa Mbu</dd>\n<dt>Country</dt><dd>TZ</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 69.96 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Radisson Blu Hotel Waterfront, Cape Town</dd>\n<dt>City</dt><dd>Cape Town</dd>\n<dt>Country</dt><dd>ZA</dd>\n<dt>Current Weather</dt><dd>broken clouds and 64.09 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Shandrani Beachcomber Resort & Spa</dd>\n<dt>City</dt><dd>Mahebourg</dd>\n<dt>Country</dt><dd>MU</dd>\n<dt>Current Weather</dt><dd>few clouds and 70.09 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>My Den Beachfront Bed and Breakfast | Self-Catering</dd>\n<dt>City</dt><dd>Port Shepstone</dd>\n<dt>Country</dt><dd>ZA</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 71.98 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Axis Porto Business & SPA Hotel</dd>\n<dt>City</dt><dd>Rio Tinto</dd>\n<dt>Country</dt><dd>PT</dd>\n<dt>Current Weather</dt><dd>clear sky and 65.28 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Casa Tia Villa</dd>\n<dt>City</dt><dd>Bambous Virieux</dd>\n<dt>Country</dt><dd>MU</dd>\n<dt>Current Weather</dt><dd>few clouds and 70.05 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Tu Casa</dd>\n<dt>City</dt><dd>East London</dd>\n<dt>Country</dt><dd>ZA</dd>\n<dt>Current Weather</dt><dd>clear sky and 67.05 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Villa Kitzia Huacho</dd>\n<dt>City</dt><dd>Hualmay</dd>\n<dt>Country</dt><dd>PE</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 64.72 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Le four à pain</dd>\n<dt>City</dt><dd>Saint-Philippe</dd>\n<dt>Country</dt><dd>RE</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 67.59 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Provincial</dd>\n<dt>City</dt><dd>San Juan</dd>\n<dt>Country</dt><dd>AR</dd>\n<dt>Current Weather</dt><dd>broken clouds and 69.19 °F</dd>\n</dl>\n']

## Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

In [35]:
# Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

# Display sample data
locations.head(10)

        Lat      Lng
1   -3.3500  35.8500
6  -33.9258  18.4232
8  -20.4081  57.7000
9  -30.7414  30.4550
10  41.1826  -8.5581
15 -20.3428  57.7575
25 -33.0153  27.9116
26 -11.0964 -77.6139
31 -21.3585  55.7679
34 -31.5375 -68.5364

## Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

In [38]:

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# Create a figure to add the Google map as a layer
fig.add_layer(marker_layer)

# Display the figure containing the map

fig

Figure(layout=FigureLayout(height='420px'))